# Sample container image with Ubuntu Jammy + Systemd
#
# Description:
#
# This image serves as a basic reference example for users looking to
# run Systemd inside a system container in order to deploy various
# services within the system container, or use it as a virtual host
# environment.
#
# Usage:
#
# $ docker run --runtime=sysbox-runc -it --rm --name=syscont nestybox/ubuntu-jammy-systemd
#
# This will run systemd and prompt for a user login; the default user/password
# in this image is "admin/admin".

FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
#
# Systemd installation
#
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        systemd \
        systemd-sysv \
        libsystemd0 \
        ca-certificates \
        dbus \
        iptables \
        htop \
        make \
        inetutils-ping \
        nano
        iproute2 \
        kmod \
        locales \
        sudo \
        udev \
        openssh-server \
        lsof \
        curl \
        socat \
        ruby-full \
        figlet \
        wireguard \
        bash-completion \
        net-tools \
        lolcat && \
        gem install lolcat && \
    \
    # Prevents journald from reading kernel messages from /dev/kmsg
    echo "ReadKMsg=no" >> /etc/systemd/journald.conf && \
    \
    # Housekeeping
    apt-get clean -y && \
    rm -rf \
        /var/cache/debconf/* \
        /var/lib/apt/lists/* \
        /var/log/* \
        /tmp/* \
        /var/tmp/* \
        /usr/share/doc/* \
        /usr/share/man/* \
        /usr/share/local/* && \
    \
    # Disable systemd services/units that are unnecessary within a container
    systemctl mask systemd-udevd.service \
                    systemd-udevd-kernel.socket \
                    systemd-udevd-control.socket \
                    systemd-modules-load.service \
                    sys-kernel-debug.mount \
                    sys-kernel-tracing.mount && \
    \
    # Start SSH service, change root password, modify bash.bashrc, install code-server
    mkdir -p /run/sshd && chmod 0755 /run/sshd \
    echo 'root:admin' | chpasswd && \
    echo "figlet -t -c youngstorage | lolcat" >> /etc/bash.bashrc && \
    echo "echo ''" >> /etc/bash.bashrc && \
    \
    # Install Docker
    curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
RUN userdel ubuntu && rm -rf /home/ubuntu
COPY setup.sh /
COPY en.json /usr/lib/code-server/out/node/i18n/locales/en.json
RUN chmod +x setup.sh
# Remove unnecessary directories
RUN rm -rf /bin.usr-is-merged /sbin.usr-is-merged /.dockerenv /get-docker.sh


